---

- name: (jekyll_install) dependencies are installed
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - ruby
    - ruby-devel
    - gcc
    - libxml2-devel
    - zlib-devel
    - redhat-rpm-config

# `state: latest` will not work
# https://centos.org/forums/viewtopic.php?t=63143&p=266016#p266047
- name: (jekyll_install) Jekyll and deps installed via gem
  gem:
    name: "{{ item.gem }}"
    version: "{{ item.version }}"
    state: present
    include_dependencies: yes
    user_install: no
  with_items: "{{ jekyll_gem_packages }}"

- name: (jekyll_install) Permissions on jekyll dir are correct
  file:
    path: "/srv/{{ httpd_webservice }}"
    owner: root
    group: apache
    mode: 0750
    recurse: no
    state: directory
