---

- name: (jekyll_config) [1/3] Jekyll skeleton deployed
  synchronize:
    src: "{{ jekyll_skeleton }}/"
    dest: "/usr/local/share/jekyll"
    archive: yes
    copy_links: yes
    rsync_opts:
      - "--exclude=.git"
      - "--no-motd"

- name: (jekyll_config) [2/3] Correct permissions on jekyll dir
  file:
    name: "/usr/local/share/jekyll"
    owner: root
    group: root
    mode: 0644
    recurse: yes

- name: (jekyll_config) [3/3] Jekyll build and deploy site remotely
  command: "jekyll build --source /usr/local/share/jekyll --destination {{ jekyll_root_dir }}"
